### ISSUE TITLE
bug(update): check update link return a 500 error

### ISSUE THREAD

**Issue by psyray** [Security-Tools-Alliance/rengine-ng#130]
### Current Behavior

When you click on the Check update entry in the top menu the check returns a 500 error
![image](https://github.com/user-attachments/assets/b9105b8d-051c-4967-9e06-147e67ef513f)

```
web-1          | django.request | Internal Server Error: /api/rengine/update/
web-1          | Traceback (most recent call last):
web-1          |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
web-1          |     response = get_response(request)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
web-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web-1          |     return view_func(*args, **kwargs)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 70, in view
web-1          |     return self.dispatch(request, *args, **kwargs)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
web-1          |     response = self.handle_exception(exc)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
web-1          |     self.raise_uncaught_exception(exc)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
web-1          |     raise exc
web-1          |   File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
web-1          |     response = handler(request, *args, **kwargs)
web-1          |   File "/usr/src/app/api/views.py", line 810, in get
web-1          |     ])[1:] if response[0]['name'][0] == 'v'
web-1          | IndexError: list index out of range
```

### Expected Behavior

Update check should return a version to compare with the current version

### Steps To Reproduce

1. Go to the Dashboard
2. Click on the entry in the User menu
![image](https://github.com/user-attachments/assets/ec596e66-57a9-4f13-a55b-6f1efed1ea40)
3. Look at the dev console or the make logs

### Environment

```markdown
- reNgine: 2.0.6
- OS: Debian 
- Python: 3.12
- Docker Engine: 27
- Docker Compose: 2.28
- Browser: FF 127
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by psyray** [comment]
Fixed by release publication
![image](https://github.com/user-attachments/assets/7f1030a2-b78d-4cbb-8803-3939c58a1c8b)
